# Generated by Django 5.2.4 on 2025-09-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('internship', 'Internship'), ('techevent', 'Tech Event')], default='techevent', max_length=20),
        ),
    ]
