# Generated by Django 5.2.4 on 2025-09-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color_theme',
            field=models.CharField(blank=True, help_text='Auto-assigned color theme', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Auto-assigned based on category', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured events get special styling'),
        ),
        migrations.AddField(
            model_name='event',
            name='styling_applied',
            field=models.BooleanField(default=False, help_text='Whether auto-styling has been applied'),
        ),
    ]
