# Generated by Django 5.2.4 on 2025-09-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_event_color_theme_event_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_details',
            field=models.TextField(blank=True, help_text='Additional information about the event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for event inquiries', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.URLField(blank=True, help_text='Registration or event website link', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prizes',
            field=models.TextField(blank=True, help_text='Prizes or benefits for participants', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True, help_text='Prerequisites or requirements for participants', null=True),
        ),
    ]
