# Generated by Django 5.2.4 on 2025-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_event_additional_details_event_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.URLField(default='https://example.com', help_text='Registration or event website link (Required)'),
            preserve_default=False,
        ),
    ]
