# Generated by Django 5.2.4 on 2025-09-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_event_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_flyer',
            field=models.ImageField(blank=True, help_text='Upload event flyer/poster', null=True, upload_to='event_flyers/'),
        ),
    ]
